import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage()
await page.goto('http://localhost:5173/login', { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
const inputs = await page.locator('input').all()
await inputs[0].fill('admin'); await inputs[1].fill('admin')
await page.click('button[type="submit"]')
await page.waitForURL('**/dashboard')
await page.waitForTimeout(1500)
await page.locator('.ant-menu-submenu-title:has-text("业务对象")').click()
await page.waitForTimeout(300)
await page.click('.ant-menu-item:has-text("物料")', { force: true })
await page.waitForURL('**/item-types/Part')
await page.waitForTimeout(1500)
await page.screenshot({ path: '/tmp/kras-list.png', fullPage: true })
console.log('HTML of thead:', await page.locator('thead').first().innerHTML())
await browser.close()
