import { chromium } from 'playwright'
const browser = await chromium.launch()
const ctx = await browser.newContext()
const page = await ctx.newPage()
await page.goto('http://localhost:5173/login', { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
const inputs = await page.locator('input').all()
await inputs[0].fill('admin'); await inputs[1].fill('admin')
await page.click('button[type="submit"]')
await page.waitForURL('**/dashboard')
await page.waitForTimeout(2500)
// 看缓存
const snap = await page.evaluate(() => localStorage.getItem('kras.meta.snapshot'))
const obj = JSON.parse(snap)
console.log('itemTypes count:', obj.itemTypes?.length)
console.log('properties count:', obj.properties?.length)
const part = obj.itemTypes?.find(t => t.name === 'Part')
console.log('Part in cache:', part?.name, part?.id)
const partProps = obj.properties?.filter(p => p.source_id === part?.id)
console.log('Part properties in cache:', partProps?.length)
console.log('sample Part prop:', partProps?.[0])
// 进列表页
await page.goto('http://localhost:5173/item-types/Part', { waitUntil: 'networkidle' })
await page.waitForTimeout(2000)
const thCount = await page.locator('thead tr').first().locator('th').count()
console.log('列表表头列数:', thCount)
const headerTexts = await page.locator('thead tr').first().locator('th').allInnerTexts()
console.log('表头:', headerTexts.join(' | '))
await browser.close()
